name: Release

on:
  push:
    tags: ['v[0-9]*']

permissions:
  contents: write

jobs:
  release:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: npm

      - name: Install glib tools
        run: sudo apt-get install -y --no-install-recommends libglib2.0-bin

      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: make pack

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: dist/*.shell-extension.zip
